default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: pguser
  password: test
  pool: 5

development:
  <<: *default
  database: philo_development


test:
  <<: *default
  database: philo_test

production:
  <<: *default
  database: philo_production
