default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: pguser
  password: test
  pool: 5

development:
  <<: *default
  database: philopedia_db_development


test:
  <<: *default
  database: philopedia_db_test

production:
  <<: *default
  database: philopedia_db_production
